### ISSUE TITLE
All my task are buried

### ISSUE THREAD

**Issue by elfeffe** [lilmuckers/magento-lilmuckers_queue#18]
I have tried with a module developed by me, and with https://github.com/MageHack/indexing
In both cases the task are buried.
Any idea about why?
I'm using beanstalkd

**Comment by lilmuckers** [comment]
If you look at `app/code/community/Magehack/Indexing/Model/Worker.php` you are calling `hold()` - this is what's burying your tasks

**Comment by elfeffe** [comment]
Yes, and probably the task in my module had some other problem.
It is working now, I will try to create a MongoDB adapter for this. I need to avoid duplicated task.
Thank you
