### ISSUE TITLE
Compatibility with CE 1.6 

### ISSUE THREAD

**Issue by raminv80** [lilmuckers/magento-lilmuckers_queue#9]
The shell script fails to run on CE 1.6. 
https://github.com/lilmuckers/magento-lilmuckers_queue/blob/master/shell/queue.php#L44 is relying on Mage_Shell_Abstract->factory which is not present in CE 1.6.

**Comment by lilmuckers** [comment]
I have no plans to make this backwards compatible for 1.6

If you swap out the calls to the factory with the standard "Mage::getModel()" calls and so forth - then I imagine it should work.


Thanks
- Patrick
